### ISSUE TITLE
touching print queue dropdown even once publishes your entry; if you press it twice quickly, it will publish the entry twice.

### ISSUE THREAD

**Issue by bisegni** [eed-web-application/elog-plus-frontend#111]
discovered by @cassidy-SLAC

**Comment by bisegni** [comment]
probably related to #110

**Comment by ngAlexander9** [comment]
Steps to replicate issue:

1. Open new entry form by clicking New Entry (top right)
2. Fill out required form data (title, logbook)
3. Click the print queue accordion. If you can click the accordion multiple times before the form closes, the post is submitted multiple times, causing duplicate entries.
