### ISSUE TITLE
Duplicate logbooks in entry

### ISSUE THREAD

**Issue by ngAlexander9** [eed-web-application/elog-plus-frontend#123]
This entry has FACILITIES twice. I assume this is undesirable.

![image](https://github.com/user-attachments/assets/e47ab0e3-18ac-4a64-9965-b175fa8b227d)

Somewhere there should be a validation check to make sure there aren't duplicates in the list of logbooks, and ideally, also a mechanism for resolving this.

**Comment by bisegni** [comment]
in which day there is the entry?

**Comment by bisegni** [comment]
is has been fixed on [pr #309](https://github.com/eed-web-application/elog-plus/pull/309). The entry with the problem has been fixed on database, when the cache will expires also the UI will be updated

**Comment by ngAlexander9** [comment]
@bisegni implemented a data cleaning step, which resolves this issue. Thank you!

![image](https://github.com/user-attachments/assets/d538ac5f-0207-4a2b-b03d-04bcc0040c89)
