### ISSUE TITLE
i got errro during build of app using docker compose

### ISSUE THREAD

**Issue by bisegni** [eed-web-application/elog-plus-frontend#14]
❯ docker compose -f elog-plus-frontend/docker-compose.yml up
Sending build context to Docker daemon   82.7kB
Step 1/18 : FROM node:16-alpine as builder
16-alpine: Pulling from library/node
31e352740f53: Already exists
a1e50b3961de: Pull complete
fdc5b5e5fbfe: Pull complete
55fd4a41ee80: Pull complete
Digest: sha256:6c381d5dc2a11dcdb693f0301e8587e43f440c90cdb8933eaaaabb905d44cdb9
Status: Downloaded newer image for node:16-alpine
 ---> d22e42cbfdbb
Step 2/18 : ENV PNPM_HOME="/pnpm"
 ---> Running in beec31820054
Removing intermediate container beec31820054
 ---> 15c43807f010
Step 3/18 : ENV PATH="$PNPM_HOME:$PATH"
 ---> Running in 26f56267575c
Removing intermediate container 26f56267575c
 ---> ae0b8e43651d
Step 4/18 : RUN corepack enable
 ---> Running in 1bff673ab9eb
Removing intermediate container 1bff673ab9eb
 ---> 977775aff07e
Step 5/18 : COPY . ./app
 ---> faf5a1500c54
Step 6/18 : WORKDIR /app
 ---> Running in d7cc35ae9525
Removing intermediate container d7cc35ae9525
 ---> 756c9d765fe5
Step 7/18 : RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
1 error occurred:
	* Status: the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled, Code: 1

(base)

**Comment by ocboogie** [comment]
Weird. Seems like you could update your docker version and it'll work, but I'll just remove caching, which should also do the trick.

**Comment by ocboogie** [comment]
Let me know if that fixed it. If not, I can reopen

**Comment by bisegni** [comment]
I'm sorry was my fault I had old config for Colima where builds was disabled

**Comment by bisegni** [comment]
I had to change the name of the service into the docker compose file app-frontend and app-backend
