### ISSUE TITLE
Mini icons should be visible also when the cursor is on the row

### ISSUE THREAD

**Issue by bisegni** [eed-web-application/elog-plus-frontend#27]

**Comment by ocboogie** [comment]
Hm, the main reason I did it this way is because it's difficult to fit everything on small screens. It's already pretty full considering tags, so with the previews as well, you won't be able to see much. For example,

![image](https://github.com/eed-web-application/elog-plus-frontend/assets/8641243/4d378dc6-c7c6-41f5-a584-b3857e6d263f)

**Comment by ocboogie** [comment]
Even if there is more space, since the previews are aligned to the right, when hovering over the row, they jump in an awkward way due to buttons becoming visible:

https://github.com/eed-web-application/elog-plus-frontend/assets/8641243/1d9cf606-7946-4f2a-90af-3803bfc557d8

**Comment by bisegni** [comment]
i this way i like it, i think is better to always show it. Anyway i like the effect

**Comment by bisegni** [comment]
> Hm, the main reason I did it this way is because it's difficult to fit everything on small screens. It's already pretty full considering tags, so with the previews as well, you won't be able to see much. For example,
> 
> ![image](https://user-images.githubusercontent.com/8641243/260071698-4d378dc6-c7c6-41f5-a584-b3857e6d263f.png)

i this case should be better to show on a 'symbol' that let you understands that has attachment, i the case of the image instead to show the minifigure could be better to show the attachment icon with a 'badge' that indicate the number. I think the mobile visualization needs to be different from the bigger UI

**Comment by ocboogie** [comment]
How does something like this look?

https://github.com/eed-web-application/elog-plus-frontend/assets/8641243/856ccd84-6003-44bf-b8ca-f856d3da78a7

**Comment by bisegni** [comment]
I think is very good
