### ISSUE TITLE
Need to fix Date/Time filter

### ISSUE THREAD

**Issue by guimanjosh** [eed-web-application/elog-plus-frontend#56]
<img width="1792" alt="Screenshot 2024-02-26 at 9 27 22 AM" src="https://github.com/eed-web-application/elog-plus-frontend/assets/122503035/211835dd-7ad9-465c-8e3a-b5a17e0d3984">

Error arises when I try to put in a VALID date to filter through the logbooks.

**Comment by guimanjosh** [comment]
<img width="1792" alt="Screenshot 2024-02-27 at 9 07 31 AM" src="https://github.com/eed-web-application/elog-plus-frontend/assets/122503035/21c44e91-ceb1-426e-8891-e4ac616a5ee3">

I believe it is a backend issue. When I try to input a date (02/07/2024), the component changes the date by itself to 01/31/2022.

**Comment by bisegni** [comment]
i think that, it cannot be a backend problem, because it doesn't return a date the can be put on that field. The backend return a list of found entry.
