### ISSUE TITLE
bug on shift update

### ISSUE THREAD

**Issue by bisegni** [eed-web-application/elog-plus-frontend#70]
I think there is a bug into the update form of the logbook, on MMC i'm trying to cerate another shift that cover update the end of the day as shown below:
![Screenshot 2024-08-05 at 9 00 41 AM](https://github.com/user-attachments/assets/83d7ce59-23b6-4e0f-9b9c-2797b35d43df)

below is the JSOn that is sent to the backend:
```
0:{name: "Owl Shift", from: "07:00", to: "14:59", id: "abc"}
1:{name: "Day Shift", from: "15:00", to: "22:59", id: "xyz"}
2:{name: "swing", from: "23:00", to: "06:59"}
```

where are came from the => 2:{name: "swing", from: "23:00", to: "06:59"}

**Comment by ocboogie** [comment]
This is expected behavior: converts to UTC and 24 hour format. What behavior were you expecting? 
<img width="1023" alt="image" src="https://github.com/user-attachments/assets/8ebb8270-93e2-44d9-8e61-0905aaf45572">

**Comment by ocboogie** [comment]
If `from` is "less than" `to`, then we have to treat as if the shift is going over midnight into the next day.

**Comment by bisegni** [comment]
on backend has been fixed

**Comment by ocboogie** [comment]
Seems like it's fixed now
