### ISSUE TITLE
Add options to make a logbook readable and writeable by anybody

### ISSUE THREAD

**Issue by mattgibbs** [eed-web-application/elog-plus-frontend#78]
Logbooks should default to being readable by anybody - very rarely does it make sense to keep the information in a logbook totally private.  Currently, there's no way to do this.

Occasionally, a logbook should be writeable by anybody, too.

These should be per-logbook options.

**Comment by mattgibbs** [comment]
This is going to take a corresponding back-end change, too.

**Comment by bisegni** [comment]
i opened on the backend as well too => https://github.com/eed-web-application/elog-plus/issues/251
