### ISSUE TITLE
remove impersonation flag when in admin view

### ISSUE THREAD

**Issue by bisegni** [eed-web-application/elog-plus-frontend#96]
admin view should be always be accessed as admin, impersonation flag should be used only into normal elog operation

**Comment by ocboogie** [comment]
This is a particularly nasty change. To have granular control over when impersonating is used, we'd have to change the API of every API interacting function (e.g., `fetchEntries`, `fetchLogbooks`, `updateLogbook`, etc.) to propagate the option into the `fetch` function. Furthermore, the idea of impersonation completely invalidates React Query's caching policy, so we'd have to specify who the user is impersonating in `queryKeys`. Obviously, we do not want to do any of this, especially considering that impersonation is supposed to mainly be a development feature.

So, the approach taken is hacky but works: 
- In `fetch`, check whether the user is impersonating and if the current route is not admin, and only then apply the `Impersonate` header.
- Use a custom `queryKeyHashFn` that checks whether the user is impersonating and if the current route is not admin, and only then concat the impersonating email to the end of the `queryKey`.

I really do not like this approach, but it's better than changing the API of every function in `api/` and changing the API of query hook that uses `useQuery`.

**Comment by bisegni** [comment]
agree
